image: golang:1.9

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - mkdir -p /go/src/github.com/bigkevmcd /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/bigkevmcd/taxi
  - ln -s /go/src/github.com/bigkevmcd /go/src/_/builds/bigkevmcd
  - make dep

unit_tests:
  stage: test
  script:
    - go test ./...

race_detector:
  stage: test
  script:
    - go test -race ./...

code_coverage:
  stage: test
  script:
    - go test 

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master

build:
  stage: build
  script:
    - go build ./src/cmd/booktaxi
